CREATE OR REPLACE PACKAGE CONTROL_JOBCHECKCOUNT IS
FUNCTION JOBCHECKCOUNT(pNumber IN NUMBER) RETURN NUMBER;
END CONTROL_JOBCHECKCOUNT;
/
CREATE OR REPLACE PACKAGE BODY CONTROL_JOBCHECKCOUNT IS
FUNCTION JOBCHECKCOUNT(pNumber IN NUMBER) RETURN NUMBER
IS vcNewRecords NUMBER(4);
BEGIN
SELECT COUNT (*)
INTO vcNewRecords
FROM criminal_record
WHERE (TRUNC(creation_date - sysdate) =0);
RETURN vcNewRecords;
END;
END CONTROL_JOBCHECKCOUNT;
/
