/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIFrames;

import java.awt.Color;

/**
 *
 * @author Ronaldo
 */
public class Login_Window extends javax.swing.JFrame {

    /**
     * Creates new form Logiin_Window
     */
    public Login_Window() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogIn_Panel = new javax.swing.JPanel();
        LogIn_Logo = new javax.swing.JLabel();
        Slogan = new javax.swing.JLabel();
        DecorationPanel = new javax.swing.JPanel();
        Username_TextField = new javax.swing.JTextField();
        Password_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LoginButton_Panel = new javax.swing.JPanel();
        Login_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogIn_Panel.setBackground(new java.awt.Color(44, 168, 109));
        LogIn_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        LogIn_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogIn_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white_logo2.png"))); // NOI18N
        LogIn_Panel.add(LogIn_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        Slogan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Slogan.setForeground(new java.awt.Color(255, 255, 255));
        Slogan.setText("Databases");
        LogIn_Panel.add(Slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 90, 30));

        DecorationPanel.setBackground(new java.awt.Color(255, 255, 255));
        DecorationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username_TextField.setBackground(new java.awt.Color(219, 219, 219));
        Username_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Username_TextField.setForeground(new java.awt.Color(153, 153, 153));
        Username_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Username_TextField.setText("Username or Email");
        Username_TextField.setBorder(null);
        Username_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Username_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Username_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Username_TextFieldMouseExited(evt);
            }
        });
        Username_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Username_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, 50));

        Password_TextField.setBackground(new java.awt.Color(219, 219, 219));
        Password_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password_TextField.setForeground(new java.awt.Color(153, 153, 153));
        Password_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password_TextField.setText("Password ");
        Password_TextField.setBorder(null);
        Password_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Password_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Password_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Password_TextFieldMouseExited(evt);
            }
        });
        Password_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Password_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 370, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Login Here");
        DecorationPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 130, 30));

        LoginButton_Panel.setBackground(new java.awt.Color(44, 168, 109));
        LoginButton_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Login_Button.setForeground(new java.awt.Color(255, 255, 255));
        Login_Button.setText("Login");
        Login_Button.setBorderPainted(false);
        Login_Button.setContentAreaFilled(false);
        Login_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseExited(evt);
            }
        });
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        LoginButton_Panel.add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        DecorationPanel.add(LoginButton_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 210, 30));

        LogIn_Panel.add(DecorationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 390, 260));

        getContentPane().add(LogIn_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 0, 600, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login_Image.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 620, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_TextFieldActionPerformed
       Username_TextField.setText("");
    }//GEN-LAST:event_Username_TextFieldActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
       
        //if type_person == admin
             Admin_Main_Menu result = new Admin_Main_Menu();
             result.setVisible(true); 
       //else
             //User_Main_Menu resultuser = new User_Main_Menu();
             //resultuser.setVisible(true);   
          this.setVisible(false);
          
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void Username_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_TextFieldMouseEntered
        Username_TextField.setBackground(new java.awt.Color(200,200,200));
        Username_TextField.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Username_TextFieldMouseEntered

    private void Username_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_TextFieldMouseExited
        Username_TextField.setBackground(new java.awt.Color(219,219,219));
        Username_TextField.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_Username_TextFieldMouseExited

    private void Password_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TextFieldMouseEntered
        Password_TextField.setBackground(new java.awt.Color(200,200,200));
        Password_TextField.setForeground(new java.awt.Color(255,255,255));

    }//GEN-LAST:event_Password_TextFieldMouseEntered

    private void Password_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TextFieldMouseExited
         Password_TextField.setBackground(new java.awt.Color(219,219,219));
         Password_TextField.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_Password_TextFieldMouseExited

    private void Password_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_TextFieldActionPerformed

    private void Login_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseEntered
        LoginButton_Panel.setBackground(new java.awt.Color(39,149,97));
    }//GEN-LAST:event_Login_ButtonMouseEntered

    private void Login_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseExited
        LoginButton_Panel.setBackground(new java.awt.Color(44,168,109));
    }//GEN-LAST:event_Login_ButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DecorationPanel;
    private javax.swing.JLabel LogIn_Logo;
    private javax.swing.JPanel LogIn_Panel;
    private javax.swing.JPanel LoginButton_Panel;
    private javax.swing.JButton Login_Button;
    private javax.swing.JTextField Password_TextField;
    private javax.swing.JLabel Slogan;
    private javax.swing.JTextField Username_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
