/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIFrames;

import java.awt.Color;

/**
 *
 * @author Ronaldo
 */
public class Register_Window extends javax.swing.JFrame {

    /**
     * Creates new form Logiin_Window
     */
    public Register_Window() {
        this.setUndecorated(true);
        initComponents();

        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogIn_Panel = new javax.swing.JPanel();
        LogIn_Logo = new javax.swing.JLabel();
        Slogan = new javax.swing.JLabel();
        DecorationPanel = new javax.swing.JPanel();
        LastName_TextField = new javax.swing.JTextField();
        Username_TextField = new javax.swing.JTextField();
        Password_TextField = new javax.swing.JTextField();
        NewUser_Label = new javax.swing.JLabel();
        RegisterButton_Panel = new javax.swing.JPanel();
        Register_Button = new javax.swing.JButton();
        Identification_TextField = new javax.swing.JTextField();
        BirthDay_DateChooser = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Email_TextField = new javax.swing.JTextField();
        Company_ComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Gender_ComboBox = new javax.swing.JComboBox<>();
        FirstName_TextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogIn_Panel.setBackground(new java.awt.Color(44, 168, 109));
        LogIn_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogIn_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white_logo2.png"))); // NOI18N
        LogIn_Panel.add(LogIn_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 70));

        Slogan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Slogan.setForeground(new java.awt.Color(255, 255, 255));
        Slogan.setText("Databases");
        LogIn_Panel.add(Slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 90, 30));

        DecorationPanel.setBackground(new java.awt.Color(255, 255, 255));
        DecorationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LastName_TextField.setBackground(new java.awt.Color(219, 219, 219));
        LastName_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LastName_TextField.setForeground(new java.awt.Color(153, 153, 153));
        LastName_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LastName_TextField.setText("Last name");
        LastName_TextField.setBorder(null);
        LastName_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        LastName_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LastName_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LastName_TextFieldMouseExited(evt);
            }
        });
        LastName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastName_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(LastName_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 260, 20));

        Username_TextField.setBackground(new java.awt.Color(219, 219, 219));
        Username_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Username_TextField.setForeground(new java.awt.Color(153, 153, 153));
        Username_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Username_TextField.setText("Username");
        Username_TextField.setBorder(null);
        Username_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Username_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Username_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Username_TextFieldMouseExited(evt);
            }
        });
        Username_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Username_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 260, 20));

        Password_TextField.setBackground(new java.awt.Color(219, 219, 219));
        Password_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password_TextField.setForeground(new java.awt.Color(153, 153, 153));
        Password_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Password_TextField.setText("Password ");
        Password_TextField.setBorder(null);
        Password_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Password_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Password_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Password_TextFieldMouseExited(evt);
            }
        });
        Password_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Password_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 20));

        NewUser_Label.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        NewUser_Label.setForeground(new java.awt.Color(0, 0, 0));
        NewUser_Label.setText("New User ");
        DecorationPanel.add(NewUser_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 120, 30));

        RegisterButton_Panel.setBackground(new java.awt.Color(44, 168, 109));
        RegisterButton_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register_Button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Register_Button.setForeground(new java.awt.Color(255, 255, 255));
        Register_Button.setText("Register Now!");
        Register_Button.setBorderPainted(false);
        Register_Button.setContentAreaFilled(false);
        Register_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Register_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Register_ButtonMouseExited(evt);
            }
        });
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });
        RegisterButton_Panel.add(Register_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 150));

        DecorationPanel.add(RegisterButton_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 160, 150));

        Identification_TextField.setBackground(new java.awt.Color(219, 219, 219));
        Identification_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Identification_TextField.setForeground(new java.awt.Color(153, 153, 153));
        Identification_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Identification_TextField.setText("Identification");
        Identification_TextField.setBorder(null);
        Identification_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Identification_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Identification_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Identification_TextFieldMouseExited(evt);
            }
        });
        Identification_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Identification_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Identification_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, 20));

        BirthDay_DateChooser.setBackground(new java.awt.Color(219, 219, 219));
        DecorationPanel.add(BirthDay_DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 160, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Company:");
        DecorationPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Birth Day:");
        DecorationPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, -1));

        Email_TextField.setBackground(new java.awt.Color(219, 219, 219));
        Email_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Email_TextField.setForeground(new java.awt.Color(153, 153, 153));
        Email_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Email_TextField.setText("Email");
        Email_TextField.setBorder(null);
        Email_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Email_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Email_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Email_TextFieldMouseExited(evt);
            }
        });
        Email_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Email_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 260, 20));

        Company_ComboBox.setBackground(new java.awt.Color(219, 219, 219));
        Company_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DecorationPanel.add(Company_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 160, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Gender:");
        DecorationPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, -1));

        Gender_ComboBox.setBackground(new java.awt.Color(219, 219, 219));
        Gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DecorationPanel.add(Gender_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 160, 20));

        FirstName_TextField1.setBackground(new java.awt.Color(219, 219, 219));
        FirstName_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FirstName_TextField1.setForeground(new java.awt.Color(153, 153, 153));
        FirstName_TextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FirstName_TextField1.setText("First name");
        FirstName_TextField1.setBorder(null);
        FirstName_TextField1.setCaretColor(new java.awt.Color(44, 168, 109));
        FirstName_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FirstName_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FirstName_TextField1MouseExited(evt);
            }
        });
        FirstName_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstName_TextField1ActionPerformed(evt);
            }
        });
        DecorationPanel.add(FirstName_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 260, 20));

        LogIn_Panel.add(DecorationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 480, 320));

        getContentPane().add(LogIn_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 520, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Register_Image.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 530, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextFieldActionPerformed

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed
        User_Main_Menu result = new User_Main_Menu();
        result.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Register_ButtonActionPerformed

    private void Username_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_TextFieldMouseEntered
        Username_TextField.setBackground(new java.awt.Color(200,200,200));
        Username_TextField.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Username_TextFieldMouseEntered

    private void Username_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_TextFieldMouseExited
        Username_TextField.setBackground(new java.awt.Color(219,219,219));
        Username_TextField.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_Username_TextFieldMouseExited

    private void Password_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TextFieldMouseEntered
        Password_TextField.setBackground(new java.awt.Color(200,200,200));
        Password_TextField.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Password_TextFieldMouseEntered

    private void Password_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TextFieldMouseExited
         Password_TextField.setBackground(new java.awt.Color(219,219,219));
         Password_TextField.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_Password_TextFieldMouseExited

    private void Password_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_TextFieldActionPerformed

    private void Register_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_ButtonMouseEntered
        RegisterButton_Panel.setBackground(new java.awt.Color(39,149,97));
    }//GEN-LAST:event_Register_ButtonMouseEntered

    private void Register_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_ButtonMouseExited
        RegisterButton_Panel.setBackground(new java.awt.Color(44,168,109));
    }//GEN-LAST:event_Register_ButtonMouseExited

    private void LastName_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastName_TextFieldMouseEntered
        LastName_TextField.setBackground(new java.awt.Color(200,200,200));
        LastName_TextField.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_LastName_TextFieldMouseEntered

    private void LastName_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastName_TextFieldMouseExited
        LastName_TextField.setBackground(new java.awt.Color(219,219,219));
        LastName_TextField.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_LastName_TextFieldMouseExited

    private void LastName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastName_TextFieldActionPerformed

    private void Identification_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Identification_TextFieldMouseEntered
        Identification_TextField.setBackground(new java.awt.Color(200,200,200));
        Identification_TextField.setForeground(new java.awt.Color(255,255,255));

    }//GEN-LAST:event_Identification_TextFieldMouseEntered

    private void Identification_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Identification_TextFieldMouseExited
        Identification_TextField.setBackground(new java.awt.Color(219,219,219));
        Identification_TextField.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_Identification_TextFieldMouseExited

    private void Identification_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Identification_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Identification_TextFieldActionPerformed

    private void Email_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Email_TextFieldMouseEntered
       Email_TextField.setBackground(new java.awt.Color(200,200,200));
       Email_TextField.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Email_TextFieldMouseEntered

    private void Email_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Email_TextFieldMouseExited
        Email_TextField.setBackground(new java.awt.Color(219,219,219));
        Email_TextField.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_Email_TextFieldMouseExited

    private void Email_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_TextFieldActionPerformed

    private void FirstName_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstName_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_TextField1MouseEntered

    private void FirstName_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstName_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_TextField1MouseExited

    private void FirstName_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstName_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_TextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser BirthDay_DateChooser;
    private javax.swing.JComboBox<String> Company_ComboBox;
    private javax.swing.JPanel DecorationPanel;
    private javax.swing.JTextField Email_TextField;
    private javax.swing.JTextField FirstName_TextField1;
    private javax.swing.JComboBox<String> Gender_ComboBox;
    private javax.swing.JTextField Identification_TextField;
    private javax.swing.JTextField LastName_TextField;
    private javax.swing.JLabel LogIn_Logo;
    private javax.swing.JPanel LogIn_Panel;
    private javax.swing.JLabel NewUser_Label;
    private javax.swing.JTextField Password_TextField;
    private javax.swing.JPanel RegisterButton_Panel;
    private javax.swing.JButton Register_Button;
    private javax.swing.JLabel Slogan;
    private javax.swing.JTextField Username_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
