/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIFrames;

/**
 *
 * @author Ronaldo
 */
public class User_Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    public User_Main_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lateral_Menu_Panel = new javax.swing.JPanel();
        Lateral_Menu_Logo = new javax.swing.JLabel();
        Profile_Panel = new javax.swing.JPanel();
        Profile_Button = new javax.swing.JButton();
        RegisterInfo_Panel = new javax.swing.JPanel();
        RegisterInfo_Button = new javax.swing.JButton();
        DangerousZones_Panel = new javax.swing.JPanel();
        DangerousZones_Button = new javax.swing.JButton();
        SearchCriminalFile_Panel = new javax.swing.JPanel();
        SearchCriminalFile_Button = new javax.swing.JButton();
        UserList_Panel = new javax.swing.JPanel();
        UserList_Button = new javax.swing.JButton();
        BannedUsers_Panel = new javax.swing.JPanel();
        BannedUsers_Button = new javax.swing.JButton();
        ExpireFiles_Panel = new javax.swing.JPanel();
        ExpireFiles_Button = new javax.swing.JButton();
        AdditionalQueries_Panel = new javax.swing.JPanel();
        AdditionalQueries_Button = new javax.swing.JButton();
        RegisterCriminalRecord_Panel = new javax.swing.JPanel();
        RegisterCriminalRecord_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Wallpaper_User_Main_Menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lateral_Menu_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Lateral_Menu_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lateral_Menu_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/panel logo.png"))); // NOI18N
        Lateral_Menu_Logo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Lateral_Menu_Panel.add(Lateral_Menu_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 10, 330, 90));

        Profile_Panel.setBackground(new java.awt.Color(219, 219, 219));
        Profile_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Profile_Button.setBackground(new java.awt.Color(235, 235, 235));
        Profile_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Profile_Button.setForeground(new java.awt.Color(102, 102, 102));
        Profile_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user icon.png"))); // NOI18N
        Profile_Button.setText("  Profile");
        Profile_Button.setBorderPainted(false);
        Profile_Button.setContentAreaFilled(false);
        Profile_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Profile_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Profile_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Profile_ButtonMouseExited(evt);
            }
        });
        Profile_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButtonActionPerformed(evt);
            }
        });
        Profile_Panel.add(Profile_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        Lateral_Menu_Panel.add(Profile_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 330, 50));

        RegisterInfo_Panel.setBackground(new java.awt.Color(219, 219, 219));
        RegisterInfo_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterInfo_Button.setBackground(new java.awt.Color(235, 235, 235));
        RegisterInfo_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RegisterInfo_Button.setForeground(new java.awt.Color(102, 102, 102));
        RegisterInfo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Register_icon.png"))); // NOI18N
        RegisterInfo_Button.setText("  Register Information");
        RegisterInfo_Button.setBorderPainted(false);
        RegisterInfo_Button.setContentAreaFilled(false);
        RegisterInfo_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RegisterInfo_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterInfo_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterInfo_ButtonMouseExited(evt);
            }
        });
        RegisterInfo_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterInfo_ButtonActionPerformed(evt);
            }
        });
        RegisterInfo_Panel.add(RegisterInfo_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 50));

        Lateral_Menu_Panel.add(RegisterInfo_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 330, 50));

        DangerousZones_Panel.setBackground(new java.awt.Color(219, 219, 219));
        DangerousZones_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DangerousZones_Button.setBackground(new java.awt.Color(235, 235, 235));
        DangerousZones_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        DangerousZones_Button.setForeground(new java.awt.Color(102, 102, 102));
        DangerousZones_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/place_icon.png"))); // NOI18N
        DangerousZones_Button.setText("  Dangerous Zones");
        DangerousZones_Button.setBorderPainted(false);
        DangerousZones_Button.setContentAreaFilled(false);
        DangerousZones_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DangerousZones_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DangerousZones_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DangerousZones_ButtonMouseExited(evt);
            }
        });
        DangerousZones_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangerousZones_ButtonActionPerformed(evt);
            }
        });
        DangerousZones_Panel.add(DangerousZones_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        Lateral_Menu_Panel.add(DangerousZones_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 320, 50));

        SearchCriminalFile_Panel.setBackground(new java.awt.Color(219, 219, 219));
        SearchCriminalFile_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchCriminalFile_Button.setBackground(new java.awt.Color(235, 235, 235));
        SearchCriminalFile_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SearchCriminalFile_Button.setForeground(new java.awt.Color(102, 102, 102));
        SearchCriminalFile_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/file_icon.png"))); // NOI18N
        SearchCriminalFile_Button.setText("  Search Criminal File");
        SearchCriminalFile_Button.setBorderPainted(false);
        SearchCriminalFile_Button.setContentAreaFilled(false);
        SearchCriminalFile_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SearchCriminalFile_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchCriminalFile_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchCriminalFile_ButtonMouseExited(evt);
            }
        });
        SearchCriminalFile_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCriminalFile_ButtonActionPerformed(evt);
            }
        });
        SearchCriminalFile_Panel.add(SearchCriminalFile_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 50));

        Lateral_Menu_Panel.add(SearchCriminalFile_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 330, 50));

        UserList_Panel.setBackground(new java.awt.Color(219, 219, 219));
        UserList_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserList_Button.setBackground(new java.awt.Color(235, 235, 235));
        UserList_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UserList_Button.setForeground(new java.awt.Color(102, 102, 102));
        UserList_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userlist_icon.png"))); // NOI18N
        UserList_Button.setText("  User List");
        UserList_Button.setBorderPainted(false);
        UserList_Button.setContentAreaFilled(false);
        UserList_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UserList_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserList_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserList_ButtonMouseExited(evt);
            }
        });
        UserList_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserList_ButtonActionPerformed(evt);
            }
        });
        UserList_Panel.add(UserList_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        Lateral_Menu_Panel.add(UserList_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 330, 50));

        BannedUsers_Panel.setBackground(new java.awt.Color(219, 219, 219));
        BannedUsers_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BannedUsers_Button.setBackground(new java.awt.Color(235, 235, 235));
        BannedUsers_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BannedUsers_Button.setForeground(new java.awt.Color(102, 102, 102));
        BannedUsers_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ban_icon.png"))); // NOI18N
        BannedUsers_Button.setText("  Banned Users");
        BannedUsers_Button.setBorderPainted(false);
        BannedUsers_Button.setContentAreaFilled(false);
        BannedUsers_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BannedUsers_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BannedUsers_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BannedUsers_ButtonMouseExited(evt);
            }
        });
        BannedUsers_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BannedUsers_ButtonActionPerformed(evt);
            }
        });
        BannedUsers_Panel.add(BannedUsers_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 300, 50));

        Lateral_Menu_Panel.add(BannedUsers_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 385, 330, 50));

        ExpireFiles_Panel.setBackground(new java.awt.Color(219, 219, 219));
        ExpireFiles_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExpireFiles_Button.setBackground(new java.awt.Color(235, 235, 235));
        ExpireFiles_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ExpireFiles_Button.setForeground(new java.awt.Color(102, 102, 102));
        ExpireFiles_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list_icon.png"))); // NOI18N
        ExpireFiles_Button.setText("  About to Expire Files");
        ExpireFiles_Button.setBorderPainted(false);
        ExpireFiles_Button.setContentAreaFilled(false);
        ExpireFiles_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExpireFiles_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExpireFiles_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExpireFiles_ButtonMouseExited(evt);
            }
        });
        ExpireFiles_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpireFiles_ButtonActionPerformed(evt);
            }
        });
        ExpireFiles_Panel.add(ExpireFiles_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 50));

        Lateral_Menu_Panel.add(ExpireFiles_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 440, 340, 50));

        AdditionalQueries_Panel.setBackground(new java.awt.Color(219, 219, 219));
        AdditionalQueries_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdditionalQueries_Button.setBackground(new java.awt.Color(235, 235, 235));
        AdditionalQueries_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AdditionalQueries_Button.setForeground(new java.awt.Color(102, 102, 102));
        AdditionalQueries_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ask_icon.png"))); // NOI18N
        AdditionalQueries_Button.setText("  Additional Queries");
        AdditionalQueries_Button.setBorderPainted(false);
        AdditionalQueries_Button.setContentAreaFilled(false);
        AdditionalQueries_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdditionalQueries_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdditionalQueries_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdditionalQueries_ButtonMouseExited(evt);
            }
        });
        AdditionalQueries_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionalQueries_ButtonActionPerformed(evt);
            }
        });
        AdditionalQueries_Panel.add(AdditionalQueries_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 50));

        Lateral_Menu_Panel.add(AdditionalQueries_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 495, 340, 50));

        RegisterCriminalRecord_Panel.setBackground(new java.awt.Color(48, 166, 109));
        RegisterCriminalRecord_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterCriminalRecord_Button.setBackground(new java.awt.Color(235, 235, 235));
        RegisterCriminalRecord_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RegisterCriminalRecord_Button.setForeground(new java.awt.Color(255, 255, 255));
        RegisterCriminalRecord_Button.setText("<html><center>Register a <p> Criminal <p> Record!");
        RegisterCriminalRecord_Button.setBorderPainted(false);
        RegisterCriminalRecord_Button.setContentAreaFilled(false);
        RegisterCriminalRecord_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterCriminalRecord_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterCriminalRecord_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterCriminalRecord_ButtonMouseExited(evt);
            }
        });
        RegisterCriminalRecord_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCriminalRecord_ButtonActionPerformed(evt);
            }
        });
        RegisterCriminalRecord_Panel.add(RegisterCriminalRecord_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 110));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("+");
        RegisterCriminalRecord_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 20, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("+");
        RegisterCriminalRecord_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("+");
        RegisterCriminalRecord_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 20, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("+");
        RegisterCriminalRecord_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 20, 30));

        Lateral_Menu_Panel.add(RegisterCriminalRecord_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 240, 110));

        getContentPane().add(Lateral_Menu_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 730));

        Wallpaper_User_Main_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Main Menu Wallpaper.png"))); // NOI18N
        getContentPane().add(Wallpaper_User_Main_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_ButtonActionPerformed

    private void UserList_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserList_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserList_ButtonActionPerformed

    private void BannedUsers_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BannedUsers_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BannedUsers_ButtonActionPerformed

    private void DangerousZones_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangerousZones_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DangerousZones_ButtonActionPerformed

    private void Profile_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_ButtonMouseEntered
        Profile_Panel.setBackground(new java.awt.Color(200,200,200));
        Profile_Button.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Profile_ButtonMouseEntered

    private void Profile_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_ButtonMouseExited
       Profile_Panel.setBackground(new java.awt.Color(219,219,219));
       Profile_Button.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_Profile_ButtonMouseExited

    private void RegisterCriminalRecord_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCriminalRecord_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterCriminalRecord_ButtonActionPerformed

    private void UserList_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserList_ButtonMouseEntered
       UserList_Panel.setBackground(new java.awt.Color(200,200,200));
       UserList_Button.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_UserList_ButtonMouseEntered

    private void UserList_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserList_ButtonMouseExited
       UserList_Panel.setBackground(new java.awt.Color(219,219,219));
       UserList_Button.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_UserList_ButtonMouseExited

    private void BannedUsers_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BannedUsers_ButtonMouseEntered
       BannedUsers_Panel.setBackground(new java.awt.Color(200,200,200));
       BannedUsers_Button.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_BannedUsers_ButtonMouseEntered

    private void BannedUsers_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BannedUsers_ButtonMouseExited
       BannedUsers_Panel.setBackground(new java.awt.Color(219,219,219));
       BannedUsers_Button.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_BannedUsers_ButtonMouseExited

    private void DangerousZones_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangerousZones_ButtonMouseEntered
       DangerousZones_Panel.setBackground(new java.awt.Color(200,200,200));
       DangerousZones_Button.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_DangerousZones_ButtonMouseEntered

    private void DangerousZones_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangerousZones_ButtonMouseExited
       DangerousZones_Panel.setBackground(new java.awt.Color(219,219,219));
       DangerousZones_Button.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_DangerousZones_ButtonMouseExited

    private void RegisterCriminalRecord_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterCriminalRecord_ButtonMouseEntered
       RegisterCriminalRecord_Panel.setBackground(new java.awt.Color(59,211,138));
    }//GEN-LAST:event_RegisterCriminalRecord_ButtonMouseEntered

    private void RegisterCriminalRecord_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterCriminalRecord_ButtonMouseExited
       RegisterCriminalRecord_Panel.setBackground(new java.awt.Color(48,166,109));
    }//GEN-LAST:event_RegisterCriminalRecord_ButtonMouseExited

    private void SearchCriminalFile_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchCriminalFile_ButtonMouseEntered
      SearchCriminalFile_Panel.setBackground(new java.awt.Color(200,200,200));
      SearchCriminalFile_Button.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_SearchCriminalFile_ButtonMouseEntered

    private void SearchCriminalFile_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchCriminalFile_ButtonMouseExited
       SearchCriminalFile_Panel.setBackground(new java.awt.Color(219,219,219));
       SearchCriminalFile_Button.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_SearchCriminalFile_ButtonMouseExited

    private void SearchCriminalFile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCriminalFile_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchCriminalFile_ButtonActionPerformed

    private void RegisterInfo_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterInfo_ButtonMouseEntered
       RegisterInfo_Panel.setBackground(new java.awt.Color(200,200,200));
       RegisterInfo_Button.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_RegisterInfo_ButtonMouseEntered

    private void RegisterInfo_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterInfo_ButtonMouseExited
       RegisterInfo_Panel.setBackground(new java.awt.Color(219,219,219));
       RegisterInfo_Button.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_RegisterInfo_ButtonMouseExited

    private void RegisterInfo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterInfo_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterInfo_ButtonActionPerformed

    private void ExpireFiles_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpireFiles_ButtonMouseEntered
     ExpireFiles_Panel.setBackground(new java.awt.Color(200,200,200));
     ExpireFiles_Button.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_ExpireFiles_ButtonMouseEntered

    private void ExpireFiles_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpireFiles_ButtonMouseExited
     ExpireFiles_Panel.setBackground(new java.awt.Color(219,219,219));
     ExpireFiles_Button.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_ExpireFiles_ButtonMouseExited

    private void ExpireFiles_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpireFiles_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpireFiles_ButtonActionPerformed

    private void AdditionalQueries_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdditionalQueries_ButtonMouseEntered
     AdditionalQueries_Panel.setBackground(new java.awt.Color(200,200,200));
     AdditionalQueries_Button.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_AdditionalQueries_ButtonMouseEntered

    private void AdditionalQueries_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdditionalQueries_ButtonMouseExited
     AdditionalQueries_Panel.setBackground(new java.awt.Color(219,219,219));
     AdditionalQueries_Button.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_AdditionalQueries_ButtonMouseExited

    private void AdditionalQueries_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionalQueries_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdditionalQueries_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdditionalQueries_Button;
    private javax.swing.JPanel AdditionalQueries_Panel;
    private javax.swing.JButton BannedUsers_Button;
    private javax.swing.JPanel BannedUsers_Panel;
    private javax.swing.JButton DangerousZones_Button;
    private javax.swing.JPanel DangerousZones_Panel;
    private javax.swing.JButton ExpireFiles_Button;
    private javax.swing.JPanel ExpireFiles_Panel;
    private javax.swing.JLabel Lateral_Menu_Logo;
    private javax.swing.JPanel Lateral_Menu_Panel;
    private javax.swing.JButton Profile_Button;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JButton RegisterCriminalRecord_Button;
    private javax.swing.JPanel RegisterCriminalRecord_Panel;
    private javax.swing.JButton RegisterInfo_Button;
    private javax.swing.JPanel RegisterInfo_Panel;
    private javax.swing.JButton SearchCriminalFile_Button;
    private javax.swing.JPanel SearchCriminalFile_Panel;
    private javax.swing.JButton UserList_Button;
    private javax.swing.JPanel UserList_Panel;
    private javax.swing.JLabel Wallpaper_User_Main_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
